import type { Metadata } from "next";
import { Hubot_Sans, Lobster } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { STYLES } from "./globals";

const geistMono = Hubot_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: "variable"
});

const fancy = Lobster({
  variable: "--font-fancy",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "PORTFOLIO 26",
  description: "Generated by create next app",
};

const styles = {
  link: "hover:brightness-125 text-white font-sans"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistMono.variable} ${fancy.variable} antialiased`}>
        <header className="lg:px-5 px-2 w-full max-w-400 absolute translate-x-[-50%] left-[50%] z-50 py-3">
          <div className="overflow-clip relative">
            <div className="w-full h-full flex-row flex items-center justify-between xl:px-5 px-2 py-2">
              <Link href="/" className="xl:text-xl lg:text-lg sm:text-md text-sm text-white relative flex flex-row gap-2 font-sans items-center justify-center group hover:brightness-125">
                <Image src="/daisy.png" alt="" height={25} width={25} />
                Portfolio 2026
              </Link>
              <nav className="flex-row gap-5 md:flex hidden text-lg">
                <Link href="/#about" className={styles.link}>
                  About
                </Link>
                <Link href="/#projects" className={styles.link}>
                  Projects
                </Link>
                <Link href="/#contact" className={styles.link}>
                  Contact
                </Link>
              </nav>
              <button aria-label="open navigation menu" className="md:hidden flex">
                <svg className="fill-white h-6 w-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640">
                  <path d="M96 160C96 142.3 110.3 128 128 128L512 128C529.7 128 544 142.3 544 160C544 177.7 529.7 192 512 192L128 192C110.3 192 96 177.7 96 160zM96 320C96 302.3 110.3 288 128 288L512 288C529.7 288 544 302.3 544 320C544 337.7 529.7 352 512 352L128 352C110.3 352 96 337.7 96 320zM544 480C544 497.7 529.7 512 512 512L128 512C110.3 512 96 497.7 96 480C96 462.3 110.3 448 128 448L512 448C529.7 448 544 462.3 544 480z"/>
                </svg>
              </button>
            </div>
          </div>
        </header>
        <div className="w-full max-w-400 m-auto min-h-screen">
          {children}
        </div>
        <footer className="bg-modal h-fit w-full max-w-400 m-auto px-5 pb-10 rounded-t-3xl mt-20 border-t-trim/20 border-t">
          <div className={STYLES.section + " pt-5!"}>
            <h2 className={STYLES.h2 + " text-mist-600! dark:text-mist-400! text-center!"}>
              Joseph Walker
            </h2> 
            <nav className="flex-row items-center justify-center gap-5 flex">
              <Link href="/#about" className={styles.link + " text-mist-600! dark:text-mist-400!"}>
                About
              </Link>
              <Link href="/#projects" className={styles.link + " text-mist-600! dark:text-mist-400!"}>
                Projects
              </Link>
              <Link href="/#contact" className={styles.link + " text-mist-600! dark:text-mist-400!"}>
                Contact
              </Link>
            </nav>
            <div className="flex flex-row items-center gap-5 w-full">
              <div className="h-px flex-1 m-auto dark:bg-trim/20 bg-mist-300/20"/>
                <svg className="fill-mist-600 dark:fill-mist-400 h-6 w-6" width="98" height="96" viewBox="0 0 98 96" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <g clipPath="url(#clip0_730_27126)">
                    <path d="M41.4395 69.3848C28.8066 67.8535 19.9062 58.7617 19.9062 46.9902C19.9062 42.2051 21.6289 37.0371 24.5 33.5918C23.2559 30.4336 23.4473 23.7344 24.8828 20.959C28.7109 20.4805 33.8789 22.4902 36.9414 25.2656C40.5781 24.1172 44.4062 23.543 49.0957 23.543C53.7852 23.543 57.6133 24.1172 61.0586 25.1699C64.0254 22.4902 69.2891 20.4805 73.1172 20.959C74.457 23.543 74.6484 30.2422 73.4043 33.4961C76.4668 37.1328 78.0937 42.0137 78.0937 46.9902C78.0937 58.7617 69.1934 67.6621 56.3691 69.2891C59.623 71.3945 61.8242 75.9883 61.8242 81.252L61.8242 91.2051C61.8242 94.0762 64.2168 95.7031 67.0879 94.5547C84.4102 87.9512 98 70.6289 98 49.1914C98 22.1074 75.9883 6.69539e-07 48.9043 4.309e-07C21.8203 1.92261e-07 -1.9479e-07 22.1074 -4.3343e-07 49.1914C-6.20631e-07 70.4375 13.4941 88.0469 31.6777 94.6504C34.2617 95.6074 36.75 93.8848 36.75 91.3008L36.75 83.6445C35.4102 84.2188 33.6875 84.6016 32.1562 84.6016C25.8398 84.6016 22.1074 81.1563 19.4277 74.7441C18.375 72.1602 17.2266 70.6289 15.0254 70.3418C13.877 70.2461 13.4941 69.7676 13.4941 69.1934C13.4941 68.0449 15.4082 67.1836 17.3223 67.1836C20.0977 67.1836 22.4902 68.9063 24.9785 72.4473C26.8926 75.2227 28.9023 76.4668 31.2949 76.4668C33.6875 76.4668 35.2187 75.6055 37.4199 73.4043C39.0469 71.7773 40.291 70.3418 41.4395 69.3848Z" />
                  </g>
                  <defs>
                    <clipPath id="clip0_730_27126">
                      <rect width="98" height="96" />
                    </clipPath>
                  </defs>
                </svg>
                <svg className="fill-mist-600 dark:fill-mist-400 h-6 w-6" height="800px" width="800px" version="1.1" id="Layer_1" viewBox="0 0 382 382">
                  <path d="M347.445,0H34.555C15.471,0,0,15.471,0,34.555v312.889C0,366.529,15.471,382,34.555,382h312.889
                    C366.529,382,382,366.529,382,347.444V34.555C382,15.471,366.529,0,347.445,0z M118.207,329.844c0,5.554-4.502,10.056-10.056,10.056
                    H65.345c-5.554,0-10.056-4.502-10.056-10.056V150.403c0-5.554,4.502-10.056,10.056-10.056h42.806
                    c5.554,0,10.056,4.502,10.056,10.056V329.844z M86.748,123.432c-22.459,0-40.666-18.207-40.666-40.666S64.289,42.1,86.748,42.1
                    s40.666,18.207,40.666,40.666S109.208,123.432,86.748,123.432z M341.91,330.654c0,5.106-4.14,9.246-9.246,9.246H286.73
                    c-5.106,0-9.246-4.14-9.246-9.246v-84.168c0-12.556,3.683-55.021-32.813-55.021c-28.309,0-34.051,29.066-35.204,42.11v97.079
                    c0,5.106-4.139,9.246-9.246,9.246h-44.426c-5.106,0-9.246-4.14-9.246-9.246V149.593c0-5.106,4.14-9.246,9.246-9.246h44.426
                    c5.106,0,9.246,4.14,9.246,9.246v15.655c10.497-15.753,26.097-27.912,59.312-27.912c73.552,0,73.131,68.716,73.131,106.472
                    L341.91,330.654L341.91,330.654z"/>
                </svg>
              <div className="h-px flex-1 m-auto dark:bg-trim/20 bg-mist-300/20"/>
            </div>
            <div className={"relative h-full overflow-clip"}>
              <div className="h-full w-full">
                <div className="h-full flex items-center justify-center px-5">
                  <p className="text-mist-600 dark:text-mist-400 font-sans text-center sm:text-sm text-xs">
                    © {new Date().getFullYear()} Frontend, backend, and infrastructure—built and measured end-to-end
                  </p>
                </div>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
