import type { Metadata } from "next";
import { Courgette, Hubot_Sans, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = JetBrains_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: "variable"
});

const geistMono = Hubot_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: "variable"
});

const fancy = Courgette({
  variable: "--font-fancy",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "PORTFOLIO 26",
  description: "Generated by create next app",
};

const styles = {
  link: "hover:brightness-125 font-mono font-light text-white"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${fancy.variable} antialiased`}>
        <header className="lg:px-5 px-2 w-full max-w-400 absolute translate-x-[-50%] left-[50%] z-50 py-3">
          <div className="overflow-clip relative">
            <div className="w-full h-full flex-row flex items-center justify-between xl:px-5 px-2 py-2">
              <Link href="/" className="xl:text-xl lg:text-lg sm:text-md text-sm text-white relative flex flex-row gap-2 items-center font-mono justify-center group hover:brightness-125">
                <Image src="/daisy.png" alt="" height={25} width={25} />
                Portfolio 2026
              </Link>
              <nav className="flex-row gap-5 md:flex hidden">
                <Link href="/#about" className={styles.link}>
                  About
                </Link>
                <Link href="/#projects" className={styles.link}>
                  Projects
                </Link>
                <Link href="/#contact" className={styles.link}>
                  Contact
                </Link>
              </nav>
              <button className="md:hidden flex">
                <svg className="fill-white h-6 w-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640">
                  <path d="M96 160C96 142.3 110.3 128 128 128L512 128C529.7 128 544 142.3 544 160C544 177.7 529.7 192 512 192L128 192C110.3 192 96 177.7 96 160zM96 320C96 302.3 110.3 288 128 288L512 288C529.7 288 544 302.3 544 320C544 337.7 529.7 352 512 352L128 352C110.3 352 96 337.7 96 320zM544 480C544 497.7 529.7 512 512 512L128 512C110.3 512 96 497.7 96 480C96 462.3 110.3 448 128 448L512 448C529.7 448 544 462.3 544 480z"/>
                </svg>
              </button>
            </div>
          </div>
        </header>
        <div className="w-full max-w-400 m-auto min-h-screen">
          {children}
        </div>
        <div className="static" />
        <footer className="h-30 w-full max-w-400 m-auto ">
          <div className={"bg-accent-two/50 relative h-full overflow-clip rounded-t-3xl"}>
            <div className="h-full w-full">
              <div className="h-full flex items-center justify-center px-5">
                <p className="text-secondary font-sans text-center sm:text-sm text-xs">
                  <strong>© {new Date().getFullYear()} Joseph Walker</strong> 
                  <br/>
                  Frontend, backend, and infrastructure—built and measured end-to-end
                </p>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
